name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install pandoc
      run: sudo apt-get install -y pandoc

    - name: Install pdflatex
      run: sudo apt-get install -y texlive-latex-recommended

    - name: Install pdflatex
      run: sudo apt-get install -y texlive-fonts-extra

    - name: Run everything
      run: make
    
    - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            document.pdf
